Checking Git status...
On branch main
Your branch is ahead of 'origin/main' by 4 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   ../.DS_Store
	modified:   ../Stock (modified content)
	modified:   ../logs/push_log_20250503.txt

no changes added to commit (use "git add" and/or "git commit -a")
Adding all changes...
Committing changes...
[main 2de4d0a] Auto sync on 2025-05-03 23:51:30
 2 files changed, 1 insertion(+), 35 deletions(-)
Pushing changes to GitHub...
To https://github.com/JackWu66/stock-data-public.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/JackWu66/stock-data-public.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Push failed
Checking Git status...
On branch main
Your branch is ahead of 'origin/main' by 5 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   ../.DS_Store
	modified:   ../Stock (modified content)
	modified:   ../logs/push_log_20250503.txt
	modified:   ../sync_data_to_github.sh

no changes added to commit (use "git add" and/or "git commit -a")
Adding all changes...
